package dam2.m6.UF2.Activitat5.entity;
// Generated 31-ene-2021 20:04:23 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Movimientos generated by hbm2java
 */
@Entity
@Table(name = "movimiento", schema="damas")
public class Movimiento  implements java.io.Serializable {
    
     @Id @GeneratedValue
     @Column(name = "idMovimento")
     private Integer idMovimiento;
      @Column(name = "idPartida")
     private Partida partida;
       @Column(name = "columnaOrigen")
     private int columnaOrigen;
        @Column(name = "columnaDestino")
     private int columnaDestino;
         @Column(name = "filaOrigen")
     private int filaOrigen;
          @Column(name = "filaDestino")
     private int filaDestino;
     
    public Movimiento() {
    }

    public Movimiento(Partida partida, int columnaOrigen, int columnaDestino, int filaOrigen, int filaDestino) {
       this.partida = partida;
       this.columnaOrigen = columnaOrigen;
       this.columnaDestino = columnaDestino;
       this.filaOrigen = filaOrigen;
       this.filaDestino = filaDestino;
    }
   
    public Integer getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(int idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }

    public int getColumnaOrigen() {
        return columnaOrigen;
    }

    public void setColumnaOrigen(int columnaOrigen) {
        this.columnaOrigen = columnaOrigen;
    }

    public int getColumnaDestino() {
        return columnaDestino;
    }

    public void setColumnaDestino(int columnaDestino) {
        this.columnaDestino = columnaDestino;
    }

    public int getFilaOrigen() {
        return filaOrigen;
    }

    public void setFilaOrigen(int filaOrigen) {
        this.filaOrigen = filaOrigen;
    }

    public int getFilaDestino() {
        return filaDestino;
    }

    public void setFilaDestino(int filaDestino) {
        this.filaDestino = filaDestino;
    }





}


