package dam2.m6.UF2.Activitat5.entity;
// Generated 31-ene-2021 20:04:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {
     
     private Integer idPartida;
     private String ganador;
     
     private Set movimientos = new HashSet(0);

    public Partida() {
    }

    public Partida(String ganador) {
        this.ganador = ganador;
    }
    public Partida(String guanyador, Set movimientos) {
       this.movimientos = movimientos;
       this.ganador = ganador;
    }
    @Id
    @GeneratedValue
    @Column(name = "idPartida")
    public Integer getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(Integer idPartida) {
        this.idPartida = idPartida;
    }
    public String getGuanyador() {
        return this.ganador;
    }
    
    public void setGuanyador(String guanyador) {
        this.ganador = guanyador;
    }
    public Set getMovimientoses() {
        return this.movimientos;
    }
    
    public void setMovimientoses(Set movimientoses) {
        this.movimientos = movimientoses;
    }




}


