package dam2.m6.UF2.Activitat5.entity;
// Generated 31-ene-2021 20:04:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private int idPartida;
     private String guanyador;
     private Set movimientoses = new HashSet(0);

    public Partida() {
    }

	
    public Partida(int idPartida, String guanyador) {
        this.idPartida = idPartida;
        this.guanyador = guanyador;
    }
    public Partida(int idPartida, String guanyador, Set movimientoses) {
       this.idPartida = idPartida;
       this.guanyador = guanyador;
       this.movimientoses = movimientoses;
    }
   
    public int getIdPartida() {
        return this.idPartida;
    }
    
    public void setIdPartida(int idPartida) {
        this.idPartida = idPartida;
    }
    public String getGuanyador() {
        return this.guanyador;
    }
    
    public void setGuanyador(String guanyador) {
        this.guanyador = guanyador;
    }
    public Set getMovimientoses() {
        return this.movimientoses;
    }
    
    public void setMovimientoses(Set movimientoses) {
        this.movimientoses = movimientoses;
    }




}


