package dam2.m6.UF2.Activitat5;
// Generated 31-ene-2021 20:04:23 by Hibernate Tools 4.3.1



/**
 * Movimientos generated by hbm2java
 */
public class Movimientos  implements java.io.Serializable {


     private int idMovimiento;
     private Partida partida;
     private int columnaInicio;
     private int columnaFinal;
     private int filaInicio;
     private int filaFinal;

    public Movimientos() {
    }

    public Movimientos(int idMovimiento, Partida partida, int columnaInicio, int columnaFinal, int filaInicio, int filaFinal) {
       this.idMovimiento = idMovimiento;
       this.partida = partida;
       this.columnaInicio = columnaInicio;
       this.columnaFinal = columnaFinal;
       this.filaInicio = filaInicio;
       this.filaFinal = filaFinal;
    }
   
    public int getIdMovimiento() {
        return this.idMovimiento;
    }
    
    public void setIdMovimiento(int idMovimiento) {
        this.idMovimiento = idMovimiento;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public int getColumnaInicio() {
        return this.columnaInicio;
    }
    
    public void setColumnaInicio(int columnaInicio) {
        this.columnaInicio = columnaInicio;
    }
    public int getColumnaFinal() {
        return this.columnaFinal;
    }
    
    public void setColumnaFinal(int columnaFinal) {
        this.columnaFinal = columnaFinal;
    }
    public int getFilaInicio() {
        return this.filaInicio;
    }
    
    public void setFilaInicio(int filaInicio) {
        this.filaInicio = filaInicio;
    }
    public int getFilaFinal() {
        return this.filaFinal;
    }
    
    public void setFilaFinal(int filaFinal) {
        this.filaFinal = filaFinal;
    }




}


