/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dam2.m3.UF6.Avaluables.Activitat7Grafic;

/**
 *
 * @author Alumne
 */
public class Interfaz extends javax.swing.JFrame {
       Fitxa[][] matriuTauler = new Fitxa[8][8];
	Tauler tauler = new Tauler(matriuTauler);
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        //Matriz tablero
        //Inicialitzem tauler
	tauler.omplirTauler();
        omplirTaulerAjedrez();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaAjedrez = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bReiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaAjedrez.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaAjedrez.setPreferredSize(new java.awt.Dimension(600, 200));
        tablaAjedrez.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAjedrezMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel1.setText("El juego del Ajedrez");

        bReiniciar.setText("Reiniciar partida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bReiniciar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tablaAjedrez, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jLabel1))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(tablaAjedrez, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(bReiniciar)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        if (tablaAjedrez.getColumnModel().getColumnCount() > 0) {
            tablaAjedrez.getColumnModel().getColumn(0).setResizable(false);
            tablaAjedrez.getColumnModel().getColumn(1).setResizable(false);
            tablaAjedrez.getColumnModel().getColumn(2).setResizable(false);
            tablaAjedrez.getColumnModel().getColumn(3).setResizable(false);
            tablaAjedrez.getColumnModel().getColumn(4).setResizable(false);
            tablaAjedrez.getColumnModel().getColumn(5).setResizable(false);
            tablaAjedrez.getColumnModel().getColumn(6).setResizable(false);
            tablaAjedrez.getColumnModel().getColumn(7).setResizable(false);
        }

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaAjedrezMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAjedrezMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaAjedrezMouseClicked
    
    private void omplirTaulerAjedrez() {
        for (int i=0;i<tablaAjedrez.getColumnCount();i++) {
            for (int j=0; j<tablaAjedrez.getRowCount();j++) {
                if (matriuTauler[i][j] != null) {
                    tablaAjedrez.setValueAt(matriuTauler[i][j], i, j);
                    //System.out.print(matriuTauler[i][j].getTipo() + " ");
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tablaAjedrez;
    // End of variables declaration//GEN-END:variables
}
